# Generated by Django 5.2 on 2025-04-17 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome_cliente", models.CharField(max_length=200)),
                ("data_pedido", models.DateField(auto_now=True)),
                ("forma_pagamento", models.CharField(max_length=100)),
                ("valor_compra", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=200)),
                ("codigo", models.CharField(max_length=8, unique=True)),
                ("quantidade", models.PositiveIntegerField()),
                ("preco_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("preco_venda", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.CharField(max_length=400)),
                (
                    "categoria_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="core.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="itemPedido",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantidade", models.PositiveIntegerField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="core.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_pedidos",
                        to="core.produto",
                    ),
                ),
            ],
        ),
    ]
