# Generated by Django 5.2 on 2025-04-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itempedido",
            old_name="subtotal",
            new_name="preco_unitario",
        ),
        migrations.AlterField(
            model_name="pedido",
            name="valor_compra",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
