# Generated by Django 5.2 on 2025-04-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_subtotal_itempedido_preco_unitario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="estoque_minimo",
            field=models.IntegerField(default=0),
        ),
    ]
